import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.sass";
import { Header } from "@/components/Header";
import { Brands } from "@/components/Brands";
import  Services  from "@/components/Services";
import { Projects } from "@/components/Projects";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NeonTech </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/logo.svg" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header/>
        <Brands/>
        <Services/>
        <Projects/>
      </main>
    </>
  );
}
